FROM node:20-alpine AS base
WORKDIR /app
RUN corepack enable

FROM base AS deps
COPY . .
RUN pnpm install --frozen-lockfile=false

FROM deps AS build
RUN pnpm --filter @expo-audit/web build

FROM node:20-alpine AS runner
WORKDIR /app
RUN corepack enable
COPY --from=build /app/apps/web/.next ./apps/web/.next
COPY --from=build /app/apps/web/public ./apps/web/public
COPY --from=deps /app/node_modules ./node_modules
COPY apps/web/package.json ./apps/web/package.json
EXPOSE 3000
CMD ["pnpm", "--filter", "@expo-audit/web", "start"]
