apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expo-audit-ingress
  namespace: expo-audit
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.expo-audit.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expo-audit-web
                port:
                  number: 80
    - host: api.expo-audit.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expo-audit-api
                port:
                  number: 80
